site_name: tools/oda-data
site_description: Python package for accessing, processing, and analyzing Official Development Assistance (ODA) data from OECD DAC

nav:
  - Home: index.md
  - Why ODA Data?: why-oda-data.md
  - Getting Started: getting-started.md
  - User Guides:
      - Working with Indicators: oecd-client.md
      - Currencies and Prices: currencies-prices.md
      - Policy Marker Analysis: policy-markers.md
      - Accessing Raw Data: data-sources.md
  - Advanced Topics:
      - Sector Imputations: sector-imputations.md
      - AidData Integration: aiddata.md
      - Cache Management: caching.md
      - Migration from v1.x: migration.md
  - Reference:
      - Contributing: contributing.md
      - Changelog: changelog.md
