name: Tests

on:
  pull_request:
    branches: [ main]

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run pytest
        run: uv run pytest --verbose

      - name: Run pytest with coverage
        if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
        run: |
          uv run pytest --cov=oda_data --cov-report=xml --cov-report=term

      - name: Upload coverage reports
        if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
